# theme: minima
title: KAZUSHI KAMIYA | VP of Engineering
description: 20年以上の経験を持つVP of Engineering。技術戦略、グローバル組織開発、AI駆動開発を推進。
show_downloads: false
google_analytics: 
logo: 

# SEO
lang: ja
author: 神谷 和志 (Kamiya Kazushi)
keywords: VP of Engineering, エンジニアリング組織, 技術戦略, AI駆動開発, マネーフォワード

# Social
twitter:
  username: tech_rusty
linkedin:
  username: kazushi-kamiya

# GitHub Pages settings
baseurl: ""
url: "https://rusty-alucard.github.io"

# Force rebuild
markdown: kramdown
highlighter: rouge
